import type { Experience } from "../types";

export const experiences: Experience[] = [
  {
    id: "fizen",
    role: "Senior React Frontend Developer",
    company: "Fizen",
    location: "Nantes",
    type: "CDI",
    period: "05/2025 - Actuel",
    hasDetail: true,
    description: [
      "Maintenance et évolution d'une application React en production, utilisée quotidiennement",
      "Participation active aux choix d'architecture front et aux décisions techniques",
      "Conception et intégration de fonctionnalités performantes et maintenables",
      "Mise en place, suivi et amélioration des tests end-to-end avec Playwright",
      "Travail en équipe agile (Kanban), revues de code, diffusion des bonnes pratiques",
      "Travail sur du code legacy avec une approche d'amélioration progressive",
      "Forte collaboration avec le produit malgré un contexte très tech",
      "Première expérience dans un modèle extrêmement structuré avec des process millimétrés",
    ],
    technologies: [
      "React",
      "React Query",
      "React Hook Form",
      "MUI",
      "Playwright",
      "Docker",
      "Git",
      "GitLab",
      "Jira",
      "HTML",
      "CSS",
    ],
  },
  {
    id: "agence16_2024",
    role: "Senior React Frontend Developer",
    company: "Agence 16",
    location: "Nantes",
    type: "CDI",
    period: "09/2024 - 05/2025",
    hasDetail: true,
    description: [
      "Projet structurant : écosystème multi-applications multi-clients entièrement automatisé",
      "Architecture d'un portail commun avec applications indépendantes à structure partagée",
      "Conception d'un design system unifié et d'un service worker global",
      "Développement d'outils de build et déploiement automatisés en Node.js",
      "Interface d'administration React connectée à un backend Node.js",
      "Mise en place d'une architecture multi-applications au sein d'une PWA (apps intégrées ou déployées indépendamment)",
      "Conception et développement d'un outil de ticketing interfacé avec Trello (API Trello)",
      "Migration d'applications de Create React App vers Vite, avec optimisation significative des temps de build",
      "Développement de scripts de pré-build Node.js pour l'automatisation des workflows",
      "Participation à la rédaction de cahiers des charges avec les équipes produit et techniques",
      "Redux poussé à son paroxysme : architecture modulaire, slices partagés, état synchronisé",
    ],
    technologies: [
      "React",
      "Redux Toolkit",
      "TypeScript",
      "Node.js",
      "Vite",
      "PWA",
      "Service Workers",
      "API Trello",
    ],
  },
  {
    id: "ocode",
    role: "React Frontend Developer",
    company: "Ocode",
    location: "Nantes",
    type: "CDI",
    period: "09/2023 - 09/2024",
    hasDetail: true,
    description: [
      "Premier environnement très structuré : équipes frontend importantes, QA dédiée, pipelines automatisés",
      "Approfondissement des patterns React : composition, render props, hooks custom, optimisation des re-renders",
      "Développement d'applications React avec un fort enjeu de performance et d'optimisation du rendu",
      "Conception d'un script Cypress sur mesure pour automatiser des scénarios multi-utilisateurs",
      "Amélioration de la fiabilité applicative grâce à une meilleure couverture de tests E2E",
      "Création d'outils Node.js pour faciliter le travail de la QA",
      "Début de l'utilisation de Node.js comme outil d'ingénierie et de scripting",
      "Collaboration active au sein d'équipes agiles (Kanban)",
    ],
    technologies: [
      "React 18",
      "Redux Toolkit",
      "TypeScript",
      "Node.js",
      "Cypress",
    ],
  },
  {
    id: "agence16_2021",
    role: "React Frontend Developer",
    company: "Agence 16",
    location: "Nantes",
    type: "CDI",
    period: "02/2021 - 09/2023",
    hasDetail: true,
    description: [
      "Développement et maintenance d'applications web et mobiles sous forme de PWA",
      "Intervention sur des applications React de différentes versions (v15 à v18)",
      "Première confrontation au code legacy et aux projets multi-clients",
      "Développement d'un système de theming automatisé : configuration d'une app en 5 minutes au lieu d'une journée",
      "Reprise d'un projet legacy critique de gestion de leads",
      "Création de plugins Vite et packages Rollup pour améliorer la modularité",
      "Mise en place d'un mono-repo pour la gestion multi-projets",
      "Automatisation de la création d'applications via des scripts Node.js",
      "Contribution à la mise en place d'un design system",
      "Optimisation UX/UI en collaboration avec les équipes design (Figma)",
    ],
    technologies: [
      "React",
      "TypeScript",
      "Redux",
      "RTK Query",
      "React Spring",
      "Sass",
      "PWA",
      "Node.js",
      "PostgreSQL",
      "Firebase",
      "Vite",
      "Rollup",
    ],
  },
  {
    id: "setavoo_cdi",
    role: "Full Stack Developer (React, Node.js)",
    company: "Setavoo",
    location: "Lille",
    type: "CDI",
    period: "09/2018 - 02/2021",
    hasDetail: true,
    description: [
      "Développement fullstack d'applications web et mobiles",
      "Refonte complète de fronts et backends existants",
      "Conception d'une application sociale orientée citoyenneté urbaine",
      "Intervention sur l'ensemble du cycle de vie : architecture, UX/UI, développement",
      "Rôle transverse : métier, fonctionnel, développement — autonomie forte",
      "Redux comme outil central d'architecture d'état applicatif",
      "Premiers pas avec PostgreSQL et structuration de données complexes",
    ],
    technologies: [
      "React",
      "React Native",
      "Redux",
      "Mapbox",
      "Node.js",
      "Express",
      "PostgreSQL",
    ],
  },
  {
    id: "setavoo_alternance",
    role: "Mobile Application Developer (React Native)",
    company: "Setavoo",
    location: "Lille",
    type: "Contrat de professionnalisation",
    period: "10/2017 - 09/2018",
    hasDetail: true,
    description: [
      "Développement d'applications mobiles React Native",
      "Développement quasi-seul de l'app 'Mes Calanques' — 20 000 utilisateurs",
      "Création d'un moteur de rendu dynamique basé sur des structures JSON",
      "Développement de parcours cartographiques avancés avec Mapbox",
      "Animations et drawer panels custom",
      "Deep-dive Redux : flux de données, reducers, gestion d'état à grande échelle",
      "Publication sur Apple Store et Google Play Store",
    ],
    technologies: ["React Native", "Redux", "Mapbox", "iOS", "Android"],
  },
  {
    id: "mairie_lille",
    role: "Full Stack Developer (React, Node.js)",
    company: "Mairie de Lille",
    location: "Lille",
    type: "Stage",
    period: "04/2017 - 10/2017",
    hasDetail: true,
    description: [
      "Conception et développement d'une application de gestion de contenu (CMS)",
      "Premier projet significatif : CMS complet en React, Express et MongoDB",
      "Projet ambitieux pour un junior — mais formateur",
      "Apprentissage des fondations de React pour vraiment maîtriser le framework",
      "Étude approfondie de la structure de données de React",
      "Optimisation de l'organisation et de l'accessibilité des informations",
    ],
    technologies: ["React", "Redux", "Node.js", "Express", "MongoDB"],
  },
  {
    id: "freelance_webdesigner",
    role: "Freelance Web Designer",
    company: "Freelance",
    location: "Lille",
    type: "Freelance",
    period: "08/2012 - 08/2015",
    hasDetail: true,
    description: [
      "Webdesign / intégration web",
      "Création webdesign et développement JavaScript de sites web",
      "Outils : Photoshop / Illustrator / Muse",
      "Technos : HTML / CSS / jQuery",
    ],
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "jQuery",
      "Photoshop",
      "Illustrator",
      "Muse",
    ],
  },
];
